### ISSUE TITLE
Export reference to inner slider object

### ISSUE THREAD

**Issue by cbenz** [Woden-app/svelte-nouislider#1]
I would like to call the [`.set()` method](https://refreshless.com/nouislider/slider-read-write/#section-setting) of the inner slider instance, like this:

```javascript
<script>
import NoUiSlider from '@woden/svelte-nouislider'

let slider
</script>

<NoUiSlider bind:slider />

<button on:click={() => { slider.set(10) }}>Set slider to 10</button>
```

I think that if you export the created instance returned by `.create()`.

**Comment by ggueyraud** [comment]
It could be a good idea to expose the slider reference to public access, or maybe we could just make a function like that to consume the nouislider set(integer) method ?
```js
export const set = value => slider.noUiSlider.set(value)
```

**Comment by cbenz** [comment]
With Svelte components wrapping other libs, it's always the same question: should we keep private the library instance? If so, each method has to be wrapped which can be a pain to maintain.

For example, I wrapped Mapbox GL with Svelte, and the `Map` class has tons of methods, so I exposed the instance (cf [this line](https://gitlab.com/jailbreak-paris/svelte-mapbox-gl/-/blob/994f1149faa5b96c9d3b3eda9127c0c1c14414b2/src/Map.svelte#L7)).

Another idea I sometimes used is to leverage Svelte "bind" mechanism. For example here we could have a `value` property that would be reactive to changes, allowing things like:

```javascript
<script>
import NoUiSlider from '@woden/svelte-nouislider'

let value
</script>

<NoUiSlider bind:value />

<button on:click={() => { value = 10 }}>Set slider to 10</button>
```

When clicking on the button, `value` would be updated, but when manipulating the slider itself, `value` would be *also* updated.

That's higher-level than exposing the inner instance, but I think both could be made, so the user could choose between reactivity style (binding a property) or imperative style (calling the instance methods directly).

Implementation of `value` would be something like:

```javascript
// In Slider.Svelte

export let value

$: sliderInstance.set(value)

slider.noUiSlider.on(
  "update",
  (values, handle, unencoded, tap, positions) => {
    value = values // or unencoded?
    dispatch("update", { values, handle, unencoded, tap, positions })
  }
)
```

(did not test it; but I plan to do it, and if it's satisfying I'll submit a real PR)

**Comment by ggueyraud** [comment]
In the new version (1.0.1) two methods has been created:
getApi() : which returns a reference to nouislider
set() : which is simply a bind to the set() method of the package

The user has now the choice between use directly the reference of nouislider or use the internal events/methods of this package
(If you think you have a better way, you can make a PR I will check it and if that is okay and what that will make the code change to merge it)
